server:
  port: 8010
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.116.133:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
